name: Publish NPM Package
run-name: 'Publish NPM Package'

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Extract version from GitHub release
        id: get_version
        run: echo "::set-output name=VERSION::${GITHUB_REF#refs/tags/}"

      - name: Publish Official Package
        run: |
          npm version --no-git-tag-version ${{ steps.get_version.outputs.VERSION }}
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
