name: Check Pull Request Labels
run-name: Check Pull Request Labels

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v3
        with:
          mode: minimum
          count: 1
          labels: 'major, minor, patch, release, skip-changelog'
